databases:
  - name: electronic-store-db
    databaseName: electronic_store
    user: electronic_store

services:
  - type: web
    name: electronic-store
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn electronic_store.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: electronic-store-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
